### ISSUE TITLE
Suggest a Textual-Visual Chat dataset

### ISSUE THREAD

**Issue by repo-atvc** [voidful/awesome-chatgpt-dataset#2]
Thanks for the curated list. We have a related work that we hope is added to this awesome repository.

Accountable Textual-Visual Chat Learns to Reject Human Instructions in Image Re-creation (https://arxiv.org/pdf/2303.05983.pdf)

Project Page: https://matrix-alpha.github.io/

**Comment by voidful** [comment]
Hi I would love to open a new file for visual and audio data, it would be appreciated to give a pr about it.
